name: Build LSPosed Module

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Grant execute permission to Gradle wrapper
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew
      continue-on-error: true

    # Step 5: Build the APK
    - name: Build APK
      run: ./gradlew assembleDebug
      continue-on-error: true

    # Step 6: Upload the APK as a build artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: LSPosed-Module-APK
        path: app/build/outputs/apk/debug/*.apk
      continue-on-error: true