name: Build LSPosed Module

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build LSPosed Module
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout your code
      uses: actions/checkout@v3

    # Step 2: Clone the LSPosed repository
    - name: Clone LSPosed repository
      run: git clone --depth=1 https://github.com/LSPosed/LSPosed.git lsposed

    # Step 3: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 4: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 5: Grant execute permission to Gradle wrapper
    - name: Make Gradle wrapper executable
      run: chmod +x lsposed/gradlew

    # Step 6: Build the APK
    - name: Build APK
      run: ./gradlew assembleDebug
      working-directory: lsposed

    # Step 7: Upload the APK as a build artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: LSPosed-Module-APK
        path: lsposed/app/build/outputs/apk/debug/*.apk
